#!/bin/sh

ffmpeg -i zap.mp4 -i mask.png -i pulse.mkv -t 8 -filter_complex '[0] crop=1580:692:200:200 [video]; [2] alphaextract,format=gbrp [pulse]; [1] alphaextract,format=gbrp [mask]; [pulse][mask] multiply=offset=0 [pulsemask]; [video][pulsemask] alphamerge,crop=606:692:0:0' -c:v libvpx-vp9 -an masked.webm
